export const countries = [
    {
        COUNTRY: "NIGERIA",
        COUNTRY_CODE: "NG"
    },
    {
    COUNTRY: "AFGHANISTAN",
    COUNTRY_CODE: "AF"
}, {
    COUNTRY: "ALAND ISLANDS",
    COUNTRY_CODE: "AX"
}, {
    COUNTRY: "ALBANIA",
    COUNTRY_CODE: "AL"
}, {
    COUNTRY: "ALGERIA",
    COUNTRY_CODE: "DZ"
}, {
    COUNTRY: "AMERICAN SAMOA",
    COUNTRY_CODE: "AS"
}, {
    COUNTRY: "ANDORRA",
    COUNTRY_CODE: "AD"
}, {
    COUNTRY: "ANGOLA",
    COUNTRY_CODE: "AO"
}, {
    COUNTRY: "ANGUILLA",
    COUNTRY_CODE: "AI"
}, {
    COUNTRY: "ANTARCTICA",
    COUNTRY_CODE: "AQ"
}, {
    COUNTRY: "ANTIGUA AND BARBUDA",
    COUNTRY_CODE: "AG"
}, {
    COUNTRY: "ARGENTINA",
    COUNTRY_CODE: "AR"
}, {
    COUNTRY: "ARMENIA",
    COUNTRY_CODE: "AM"
}, {
    COUNTRY: "ARUBA",
    COUNTRY_CODE: "AW"
}, {
    COUNTRY: "AUSTRALIA",
    COUNTRY_CODE: "AU"
}, {
    COUNTRY: "AUSTRIA",
    COUNTRY_CODE: "AT"
}, {
    COUNTRY: "AZERBAIJAN",
    COUNTRY_CODE: "AZ"
}, {
    COUNTRY: "BAHAMAS",
    COUNTRY_CODE: "BS"
}, {
    COUNTRY: "BAHRAIN",
    COUNTRY_CODE: "BH"
}, {
    COUNTRY: "BANGLADESH",
    COUNTRY_CODE: "BD"
}, {
    COUNTRY: "BARBADOS",
    COUNTRY_CODE: "BB"
}, {
    COUNTRY: "BELARUS",
    COUNTRY_CODE: "BY"
}, {
    COUNTRY: "BELGIUM",
    COUNTRY_CODE: "BE"
}, {
    COUNTRY: "BELIZE",
    COUNTRY_CODE: "BZ"
}, {
    COUNTRY: "BENIN",
    COUNTRY_CODE: "BJ"
}, {
    COUNTRY: "BERMUDA",
    COUNTRY_CODE: "BM"
}, {
    COUNTRY: "BHUTAN",
    COUNTRY_CODE: "BT"
}, {
    COUNTRY: "BOLIVIA",
    COUNTRY_CODE: "BO"
}, {
    COUNTRY: "BOSNIA AND HERZEGOVINA",
    COUNTRY_CODE: "BA"
}, {
    COUNTRY: "BOTSWANA",
    COUNTRY_CODE: "BW"
}, {
    COUNTRY: "BOUVET ISLAND",
    COUNTRY_CODE: "BV"
}, {
    COUNTRY: "BRAZIL",
    COUNTRY_CODE: "BR"
}, {
    COUNTRY: "BRITISH INDIAN OCEAN TERRITORY",
    COUNTRY_CODE: "IO"
}, {
    COUNTRY: "BRUNEI DARUSSALAM",
    COUNTRY_CODE: "BN"
}, {
    COUNTRY: "BULGARIA",
    COUNTRY_CODE: "BG"
}, {
    COUNTRY: "BURKINA FASO",
    COUNTRY_CODE: "BF"
}, {
    COUNTRY: "BURUNDI",
    COUNTRY_CODE: "BI"
}, {
    COUNTRY: "CAMBODIA",
    COUNTRY_CODE: "KH"
}, {
    COUNTRY: "CAMEROON",
    COUNTRY_CODE: "CM"
}, {
    COUNTRY: "CANADA",
    COUNTRY_CODE: "CA"
}, {
    COUNTRY: "CAPE VERDE",
    COUNTRY_CODE: "CV"
}, {
    COUNTRY: "CAYMAN ISLANDS",
    COUNTRY_CODE: "KY"
}, {
    COUNTRY: "CENTRAL AFRICAN REPUBLIC",
    COUNTRY_CODE: "CF"
}, {
    COUNTRY: "CHAD",
    COUNTRY_CODE: "TD"
}, {
    COUNTRY: "CHILE",
    COUNTRY_CODE: "CL"
}, {
    COUNTRY: "CHINA",
    COUNTRY_CODE: "CN"
}, {
    COUNTRY: "CHRISTMAS ISLAND",
    COUNTRY_CODE: "CX"
}, {
    COUNTRY: "COCOS (KEELING) ISLANDS",
    COUNTRY_CODE: "CC"
}, {
    COUNTRY: "COLOMBIA",
    COUNTRY_CODE: "CO"
}, {
    COUNTRY: "COMOROS",
    COUNTRY_CODE: "KM"
}, {
    COUNTRY: "CONGO",
    COUNTRY_CODE: "CG"
}, {
    COUNTRY: "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
    COUNTRY_CODE: "CD"
}, {
    COUNTRY: "COOK ISLANDS",
    COUNTRY_CODE: "CK"
}, {
    COUNTRY: "COSTA RICA",
    COUNTRY_CODE: "CR"
}, {
    COUNTRY: "COTE DIVOIRE",
    COUNTRY_CODE: "CI"
}, {
    COUNTRY: "CROATIA",
    COUNTRY_CODE: "HR"
}, {
    COUNTRY: "CUBA",
    COUNTRY_CODE: "CU"
}, {
    COUNTRY: "CYPRUS",
    COUNTRY_CODE: "CY"
}, {
    COUNTRY: "CZECH REPUBLIC",
    COUNTRY_CODE: "CZ"
}, {
    COUNTRY: "DENMARK",
    COUNTRY_CODE: "DK"
}, {
    COUNTRY: "DJIBOUTI",
    COUNTRY_CODE: "DJ"
}, {
    COUNTRY: "DOMINICA",
    COUNTRY_CODE: "DM"
}, {
    COUNTRY: "DOMINICAN REPUBLIC",
    COUNTRY_CODE: "DO"
}, {
    COUNTRY: "ECUADOR",
    COUNTRY_CODE: "EC"
}, {
    COUNTRY: "EGYPT",
    COUNTRY_CODE: "EG"
}, {
    COUNTRY: "EL SALVADOR",
    COUNTRY_CODE: "SV"
}, {
    COUNTRY: "EQUATORIAL GUINEA",
    COUNTRY_CODE: "GQ"
}, {
    COUNTRY: "ERITREA",
    COUNTRY_CODE: "ER"
}, {
    COUNTRY: "ESTONIA",
    COUNTRY_CODE: "EE"
}, {
    COUNTRY: "ETHIOPIA",
    COUNTRY_CODE: "ET"
}, {
    COUNTRY: "EUROPEAN UNION",
    COUNTRY_CODE: "EU"
}, {
    COUNTRY: "FALKLAND ISLANDS (MALVINAS)",
    COUNTRY_CODE: "FK"
}, {
    COUNTRY: "FAROE ISLANDS",
    COUNTRY_CODE: "FO"
}, {
    COUNTRY: "FIJI",
    COUNTRY_CODE: "FJ"
}, {
    COUNTRY: "FINLAND",
    COUNTRY_CODE: "FI"
}, {
    COUNTRY: "FRANCE",
    COUNTRY_CODE: "FR"
}, {
    COUNTRY: "FRENCH GUIANA",
    COUNTRY_CODE: "GF"
}, {
    COUNTRY: "FRENCH POLYNESIA",
    COUNTRY_CODE: "PF"
}, {
    COUNTRY: "FRENCH SOUTHERN TERRITORIES",
    COUNTRY_CODE: "TF"
}, {
    COUNTRY: "GABON",
    COUNTRY_CODE: "GA"
}, {
    COUNTRY: "GAMBIA",
    COUNTRY_CODE: "GM"
}, {
    COUNTRY: "GEORGIA",
    COUNTRY_CODE: "GE"
}, {
    COUNTRY: "GERMANY",
    COUNTRY_CODE: "DE"
}, {
    COUNTRY: "GHANA",
    COUNTRY_CODE: "GH"
}, {
    COUNTRY: "GIBRALTAR",
    COUNTRY_CODE: "GI"
}, {
    COUNTRY: "GREECE",
    COUNTRY_CODE: "GR"
}, {
    COUNTRY: "GREENLAND",
    COUNTRY_CODE: "GL"
}, {
    COUNTRY: "GRENADA",
    COUNTRY_CODE: "GD"
}, {
    COUNTRY: "GUADELOUPE",
    COUNTRY_CODE: "GP"
}, {
    COUNTRY: "GUAM",
    COUNTRY_CODE: "GU"
}, {
    COUNTRY: "GUATEMALA",
    COUNTRY_CODE: "GT"
}, {
    COUNTRY: "GUERNSEY",
    COUNTRY_CODE: "GG"
}, {
    COUNTRY: "GUINEA",
    COUNTRY_CODE: "GN"
}, {
    COUNTRY: "GUINEA BISSAU",
    COUNTRY_CODE: "GW"
}, {
    COUNTRY: "GUYANA",
    COUNTRY_CODE: "GY"
}, {
    COUNTRY: "HAITI",
    COUNTRY_CODE: "HT"
}, {
    COUNTRY: "HEARD ISLAND AND MCDONALD ISLANDS",
    COUNTRY_CODE: "HM"
}, {
    COUNTRY: "HOLY SEE (VATICAN CITY STATE)",
    COUNTRY_CODE: "VA"
}, {
    COUNTRY: "HONDURAS",
    COUNTRY_CODE: "HN"
}, {
    COUNTRY: "HONG KONG",
    COUNTRY_CODE: "HK"
}, {
    COUNTRY: "HUNGARY",
    COUNTRY_CODE: "HU"
}, {
    COUNTRY: "ICELAND",
    COUNTRY_CODE: "IS"
}, {
    COUNTRY: "INDIA",
    COUNTRY_CODE: "IN"
}, {
    COUNTRY: "INDONESIA",
    COUNTRY_CODE: "ID"
}, {
    COUNTRY: "IRAN, ISLAMIC REPUBLIC OF",
    COUNTRY_CODE: "IR"
}, {
    COUNTRY: "IRAQ",
    COUNTRY_CODE: "IQ"
}, {
    COUNTRY: "IRELAND",
    COUNTRY_CODE: "IE"
}, {
    COUNTRY: "ISLE OF MAN",
    COUNTRY_CODE: "IM"
}, {
    COUNTRY: "ISRAEL",
    COUNTRY_CODE: "IL"
}, {
    COUNTRY: "ITALY",
    COUNTRY_CODE: "IT"
}, {
    COUNTRY: "JAMAICA",
    COUNTRY_CODE: "JM"
}, {
    COUNTRY: "JAPAN",
    COUNTRY_CODE: "JP"
}, {
    COUNTRY: "JERSEY",
    COUNTRY_CODE: "JE"
}, {
    COUNTRY: "JORDAN",
    COUNTRY_CODE: "JO"
}, {
    COUNTRY: "KAZAKHSTAN",
    COUNTRY_CODE: "KZ"
}, {
    COUNTRY: "KENYA",
    COUNTRY_CODE: "KE"
}, {
    COUNTRY: "KIRIBATI",
    COUNTRY_CODE: "KI"
}, {
    COUNTRY: "KOREA, DEMOCRATIC PEOPLES REPUBLIC OF",
    COUNTRY_CODE: "KP"
}, {
    COUNTRY: "KOREA, REPUBLIC OF",
    COUNTRY_CODE: "KR"
}, {
    COUNTRY: "KUWAIT",
    COUNTRY_CODE: "KW"
}, {
    COUNTRY: "KYRGYZSTAN",
    COUNTRY_CODE: "KG"
}, {
    COUNTRY: "LAO PEOPLES DEMOCRATIC REPUBLIC",
    COUNTRY_CODE: "LA"
}, {
    COUNTRY: "LATVIA",
    COUNTRY_CODE: "LV"
}, {
    COUNTRY: "LEBANON",
    COUNTRY_CODE: "LB"
}, {
    COUNTRY: "LESOTHO",
    COUNTRY_CODE: "LS"
}, {
    COUNTRY: "LIBERIA",
    COUNTRY_CODE: "LR"
}, {
    COUNTRY: "LIBYAN ARAB JAMAHIRIYA",
    COUNTRY_CODE: "LY"
}, {
    COUNTRY: "LIECHTENSTEIN",
    COUNTRY_CODE: "LI"
}, {
    COUNTRY: "LITHUANIA",
    COUNTRY_CODE: "LT"
}, {
    COUNTRY: "LUXEMBOURG",
    COUNTRY_CODE: "LU"
}, {
    COUNTRY: "MACAO",
    COUNTRY_CODE: "MO"
}, {
    COUNTRY: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
    COUNTRY_CODE: "MK"
}, {
    COUNTRY: "MADAGASCAR",
    COUNTRY_CODE: "MG"
}, {
    COUNTRY: "MALAWI",
    COUNTRY_CODE: "MW"
}, {
    COUNTRY: "MALAYSIA",
    COUNTRY_CODE: "MY"
}, {
    COUNTRY: "MALDIVES",
    COUNTRY_CODE: "MV"
}, {
    COUNTRY: "MALI",
    COUNTRY_CODE: "ML"
}, {
    COUNTRY: "MALTA",
    COUNTRY_CODE: "MT"
}, {
    COUNTRY: "MARSHALL ISLANDS",
    COUNTRY_CODE: "MH"
}, {
    COUNTRY: "MARTINIQUE",
    COUNTRY_CODE: "MQ"
}, {
    COUNTRY: "MAURITANIA",
    COUNTRY_CODE: "MR"
}, {
    COUNTRY: "MAURITIUS",
    COUNTRY_CODE: "MU"
}, {
    COUNTRY: "MAYOTTE",
    COUNTRY_CODE: "YT"
}, {
    COUNTRY: "MEXICO",
    COUNTRY_CODE: "MX"
}, {
    COUNTRY: "MICRONESIA, FEDERATED STATES OF",
    COUNTRY_CODE: "FM"
}, {
    COUNTRY: "MOLDOVA, REPUBLIC OF",
    COUNTRY_CODE: "MD"
}, {
    COUNTRY: "MONACO",
    COUNTRY_CODE: "MC"
}, {
    COUNTRY: "MONGOLIA",
    COUNTRY_CODE: "MN"
}, {
    COUNTRY: "MONTENEGRO",
    COUNTRY_CODE: "ME"
}, {
    COUNTRY: "MONTSERRAT",
    COUNTRY_CODE: "MS"
}, {
    COUNTRY: "MOROCCO",
    COUNTRY_CODE: "MA"
}, {
    COUNTRY: "MOZAMBIQUE",
    COUNTRY_CODE: "MZ"
}, {
    COUNTRY: "MYANMAR",
    COUNTRY_CODE: "MM"
}, {
    COUNTRY: "NAURU",
    COUNTRY_CODE: "NR"
}, {
    COUNTRY: "NEPAL",
    COUNTRY_CODE: "NP"
}, {
    COUNTRY: "NETHERLANDS",
    COUNTRY_CODE: "NL"
}, {
    COUNTRY: "NETHERLANDS ANTILLES",
    COUNTRY_CODE: "AN"
}, {
    COUNTRY: "NEW CALEDONIA",
    COUNTRY_CODE: "NC"
}, {
    COUNTRY: "NEW ZEALAND",
    COUNTRY_CODE: "NZ"
}, {
    COUNTRY: "NICARAGUA",
    COUNTRY_CODE: "NI"
}, {
    COUNTRY: "NIGER",
    COUNTRY_CODE: "NE"
}, {
    COUNTRY: "NIUE",
    COUNTRY_CODE: "NU"
}, {
    COUNTRY: "NORFOLK ISLAND",
    COUNTRY_CODE: "NF"
}, {
    COUNTRY: "NORTHERN MARIANA ISLANDS",
    COUNTRY_CODE: "MP"
}, {
    COUNTRY: "NORWAY",
    COUNTRY_CODE: "NO"
}, {
    COUNTRY: "OMAN",
    COUNTRY_CODE: "OM"
}, {
    COUNTRY: "PAKISTAN",
    COUNTRY_CODE: "PK"
}, {
    COUNTRY: "PALAU",
    COUNTRY_CODE: "PW"
}, {
    COUNTRY: "PALESTINIAN TERRITORY, OCCUPIED",
    COUNTRY_CODE: "PS"
}, {
    COUNTRY: "PANAMA",
    COUNTRY_CODE: "PA"
}, {
    COUNTRY: "PAPUA NEW GUINEA",
    COUNTRY_CODE: "PG"
}, {
    COUNTRY: "PARAGUAY",
    COUNTRY_CODE: "PY"
}, {
    COUNTRY: "PERU",
    COUNTRY_CODE: "PE"
}, {
    COUNTRY: "PHILIPPINES",
    COUNTRY_CODE: "PH"
}, {
    COUNTRY: "PITCAIRN",
    COUNTRY_CODE: "PN"
}, {
    COUNTRY: "POLAND",
    COUNTRY_CODE: "PL"
}, {
    COUNTRY: "PORTUGAL",
    COUNTRY_CODE: "PT"
}, {
    COUNTRY: "PUERTO RICO",
    COUNTRY_CODE: "PR"
}, {
    COUNTRY: "QATAR",
    COUNTRY_CODE: "QA"
}, {
    COUNTRY: "REUNION",
    COUNTRY_CODE: "RE"
}, {
    COUNTRY: "ROMANIA",
    COUNTRY_CODE: "RO"
}, {
    COUNTRY: "RUSSIAN FEDERATION",
    COUNTRY_CODE: "RU"
}, {
    COUNTRY: "RWANDA",
    COUNTRY_CODE: "RW"
}, {
    COUNTRY: "SAINT HELENA",
    COUNTRY_CODE: "SH"
}, {
    COUNTRY: "SAINT KITTS AND NEVIS",
    COUNTRY_CODE: "KN"
}, {
    COUNTRY: "SAINT LUCIA",
    COUNTRY_CODE: "LC"
}, {
    COUNTRY: "SAINT PIERRE AND MIQUELON",
    COUNTRY_CODE: "PM"
}, {
    COUNTRY: "SAINT VINCENT AND THE GRENADINES",
    COUNTRY_CODE: "VC"
}, {
    COUNTRY: "SAMOA",
    COUNTRY_CODE: "WS"
}, {
    COUNTRY: "SAN MARINO",
    COUNTRY_CODE: "SM"
}, {
    COUNTRY: "SAO TOME AND PRINCIPE",
    COUNTRY_CODE: "ST"
}, {
    COUNTRY: "SAUDI ARABIA",
    COUNTRY_CODE: "SA"
}, {
    COUNTRY: "SENEGAL",
    COUNTRY_CODE: "SN"
}, {
    COUNTRY: "SERBIA",
    COUNTRY_CODE: "RS"
}, {
    COUNTRY: "SEYCHELLES",
    COUNTRY_CODE: "SC"
}, {
    COUNTRY: "SIERRA LEONE",
    COUNTRY_CODE: "SL"
}, {
    COUNTRY: "SINGAPORE",
    COUNTRY_CODE: "SG"
}, {
    COUNTRY: "SLOVAKIA",
    COUNTRY_CODE: "SK"
}, {
    COUNTRY: "SLOVENIA",
    COUNTRY_CODE: "SI"
}, {
    COUNTRY: "SOLOMON ISLANDS",
    COUNTRY_CODE: "SB"
}, {
    COUNTRY: "SOMALIA",
    COUNTRY_CODE: "SO"
}, {
    COUNTRY: "SOUTH AFRICA",
    COUNTRY_CODE: "ZA"
}, {
    COUNTRY: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    COUNTRY_CODE: "GS"
}, {
    COUNTRY: "SPAIN",
    COUNTRY_CODE: "ES"
}, {
    COUNTRY: "SRI LANKA",
    COUNTRY_CODE: "LK"
}, {
    COUNTRY: "SUDAN",
    COUNTRY_CODE: "SD"
}, {
    COUNTRY: "SURINAME",
    COUNTRY_CODE: "SR"
}, {
    COUNTRY: "SVALBARD AND JAN MAYEN",
    COUNTRY_CODE: "SJ"
}, {
    COUNTRY: "SWAZILAND",
    COUNTRY_CODE: "SZ"
}, {
    COUNTRY: "SWEDEN",
    COUNTRY_CODE: "SE"
}, {
    COUNTRY: "SWITZERLAND",
    COUNTRY_CODE: "CH"
}, {
    COUNTRY: "SYRIAN ARAB REPUBLIC",
    COUNTRY_CODE: "SY"
}, {
    COUNTRY: "TAIWAN, PROVINCE OF CHINA",
    COUNTRY_CODE: "TW"
}, {
    COUNTRY: "TAJIKISTAN",
    COUNTRY_CODE: "TJ"
}, {
    COUNTRY: "TANZANIA, UNITED REPUBLIC OF",
    COUNTRY_CODE: "TZ"
}, {
    COUNTRY: "THAILAND",
    COUNTRY_CODE: "TH"
}, {
    COUNTRY: "TIMOR LESTE",
    COUNTRY_CODE: "TL"
}, {
    COUNTRY: "TOGO",
    COUNTRY_CODE: "TG"
}, {
    COUNTRY: "TOKELAU",
    COUNTRY_CODE: "TK"
}, {
    COUNTRY: "TONGA",
    COUNTRY_CODE: "TO"
}, {
    COUNTRY: "TRINIDAD AND TOBAGO",
    COUNTRY_CODE: "TT"
}, {
    COUNTRY: "TUNISIA",
    COUNTRY_CODE: "TN"
}, {
    COUNTRY: "TURKEY",
    COUNTRY_CODE: "TR"
}, {
    COUNTRY: "TURKMENISTAN",
    COUNTRY_CODE: "TM"
}, {
    COUNTRY: "TURKS AND CAICOS ISLANDS",
    COUNTRY_CODE: "TC"
}, {
    COUNTRY: "TUVALU",
    COUNTRY_CODE: "TV"
}, {
    COUNTRY: "UGANDA",
    COUNTRY_CODE: "UG"
}, {
    COUNTRY: "UKRAINE",
    COUNTRY_CODE: "UA"
}, {
    COUNTRY: "UNITED ARAB EMIRATES",
    COUNTRY_CODE: "AE"
}, {
    COUNTRY: "UNITED KINGDOM",
    COUNTRY_CODE: "GB"
}, {
    COUNTRY: "UNITED STATES",
    COUNTRY_CODE: "US"
}, {
    COUNTRY: "UNITED STATES MINOR OUTLYING ISLANDS",
    COUNTRY_CODE: "UM"
}, {
    COUNTRY: "URUGUAY",
    COUNTRY_CODE: "UY"
}, {
    COUNTRY: "UZBEKISTAN",
    COUNTRY_CODE: "UZ"
}, {
    COUNTRY: "VANUATU",
    COUNTRY_CODE: "VU"
}, {
    COUNTRY: "VENEZUELA",
    COUNTRY_CODE: "VE"
}, {
    COUNTRY: "VIET NAM",
    COUNTRY_CODE: "VN"
}, {
    COUNTRY: "VIRGIN ISLANDS, BRITISH",
    COUNTRY_CODE: "VG"
}, {
    COUNTRY: "VIRGIN ISLANDS, U.S.",
    COUNTRY_CODE: "VI"
}, {
    COUNTRY: "WALLIS AND FUTUNA",
    COUNTRY_CODE: "WF"
}, {
    COUNTRY: "WESTERN SAHARA",
    COUNTRY_CODE: "EH"
}, {
    COUNTRY: "YEMEN",
    COUNTRY_CODE: "YE"
}, {
    COUNTRY: "ZAMBIA",
    COUNTRY_CODE: "ZM"
}, {
    COUNTRY: "ZIMBABWE",
    COUNTRY_CODE: "ZW"
}, {
    COUNTRY: "OTHER",
    COUNTRY_CODE: "OTHER"
}, {
    COUNTRY: "NAMIBIA",
    COUNTRY_CODE: "NA"
}]
